<?php
	$MYTHEME_SPAMTRAP_SEP = array( ".", ".", "-", "_", "_", "", "" );
	$MYTHEME_SPAMTRAP_FNAMES = array(
		  "zella", "lanny", "ariane", "josphine", "latonia", "morton"
		, "lesha", "youlanda", "dyan", "lucille", "sherlene", "veronique"
		, "kaila", "cristin", "dovie", "trish", "tobias", "chantay"
		, "marlon", "roma", "rey", "mikel", "barrie", "gus"
		, "janee", "consuelo", "mohammad", "clemente", "valda", "jeremiah"
		, "jami", "somer", "tinisha", "joi", "ferne", "ronny"
		, "jeanetta", "shaunna", "allie", "venus", "sherlyn", "agripina"
		, "kent", "jerrell", "melissa", "rudolf", "janell", "annis"
		, "angelena", "delena", "meagan", "kam", "zachary", "velvet"
		, "leta", "hiedi", "angelina", "dayle", "paulita", "garth"
		, "joelle", "kary", "marylee", "crystle", "nydia", "willene"
		, "hans", "anya", "trisha", "wendie", "sunni", "ignacia"
		, "dorthea", "jenna", "lizbeth", "jamee", "isaias", "star"
		, "gillian", "kirstin", "terence", "pinkie", "majorie", "hamid"
		, "veda", "caryl", "marianna", "athena", "ian", "isa"
		, "floyd", "marquitta", "dierdre", "niesha", "fatima", "tonita"
		, "victoria", "aline", "kathrin", "andres", "palma", "mariella"
		, "novella", "earnestine", "veola", "kristian", "larry", "keesha"
		, "libby", "soledad", "adelina", "seth", "keshia", "charlesetta"
		, "deja", "jone", "kasha", "refugia", "january", "tula"
		, "daniela", "jeannetta", "estella", "gwendolyn", "brittanie", "scarlet"
		, "virgen", "joya", "frederick", "antione", "kimberley", "suzan"
		, "jean", "gavin", "karon", "lavone", "ettie", "sheba"
		, "sally", "tamela", "samual", "cinda", "maddie", "selma"
		, "alma", "rina", "asa", "jennifer", "trista", "olympia"
		
	);
	$MYTHEME_SPAMTRAP_LNAMES = array(
		  "bendetti", "golombek", "alas", "dunzelman", "kaull", "gurrero"
		, "ruschmann", "hurban", "gunzelman", "robertshaw", "rafuse", "branaugh"
		, "louvier", "kostelnik", "engebretson", "valez", "meldahl", "vacha"
		, "cardiff", "kantarian", "konieczko", "sakry", "strauf", "sep"
		, "kruebbe", "heally", "reem", "neyer", "donahey", "shandley"
		, "namaka", "soloveichik", "kennady", "lowdermilk", "gesmondi", "tanaka"
		, "retz", "figliola", "fechtig", "makowsky", "denault", "orlof"
		, "stermer", "villaneuva", "aycock", "ruddell", "hamway", "keasley"
		, "bierstedt", "bourdier", "huch", "gillock", "kleimola", "hesketh"
		, "kurylo", "longfellow", "kaina", "dulek", "buresh", "catrambone"
		, "partlow", "shade", "jn", "rexford", "vannatten", "gearn"
		, "martie", "capell", "goicoechea", "mcquaig", "ferrebee", "perretta"
		, "fosser", "jacka", "hilyard", "croyle", "kossack", "cafourek"
		, "fason", "baldree", "borgeson", "fenk", "bettinson", "rintharamy"
		, "paganini", "freeby", "schearer", "gittleman", "coughran", "galliher"
		, "ertman", "haines", "sifre", "ee", "vandyk", "szilagyi"
		, "applonie", "sharma", "rodamis", "barstow", "fissori", "notowitz"
		, "tunks", "persinger", "sumner", "mottet", "daddario", "cera"
		, "rollf", "shin", "kimbrell", "nardo", "wippert", "shey"
		, "tew", "epperley", "simoson", "blimka", "maben", "samano"
		, "cazier", "devilliers", "dettor", "felicione", "nuque", "blyzes"
		, "launius", "falconeri", "drapkin", "monagas", "wiltberger", "kamen"
		, "perego", "wold", "mosiman", "millikin", "trafford", "sweezy"
		, "mahal", "waxler", "hynson", "odom", "koets", "mingledorff"
		, "leppink", "fullerton", "gurevich", "gunning", "shawber", "herandez"
		
	);
?>