<?php
$options = array(
	array(
        "name" => __("Horizontal Dropdown Menu", 'ultimatum'),
        "type" => "start"
    ),
    array(
        "name" => __("Margins ", 'ultimatum'),
        "id" => "cssvar48",
        'type' => 'margins',
        'margin-top'=>true,
        'margin-bottom'=>true,
    ),
	array(
        "name" => __("Sub Item Width ", 'ultimatum'),
        "id" => "cssvar49",
        "property" =>"width",
        "default" => "200",
        "type" => "textCSS",
    ),
    array(
        "name" => __("Top Level Items Background ", 'ultimatum'),
        "id" => "cssvar50",
        "property" =>"background-color",
        "default" => "",
        "type" => "color"
    ),
    array(
        "name" => __("Top Level Hover and sub items background ", 'ultimatum'),
        "id" => "cssvar51",
        "property" =>"background-color",
        "default" => "",
        "type" => "color"
    ),
    array(
        "name" => __("Top Level Active Item background ", 'ultimatum'),
        "id" => "cssvar115",
        "property" =>"background-color",
        "default" => "",
        "type" => "color"
    ),
    array(
        "name" => __("Sub Levels Hover background ", 'ultimatum'),
        "id" => "cssvar52",
        "property" =>"background-color",
        "default" => "",
        "type" => "color"
    ),
    array(
        'id' => 'cssvar53',
        'name' => __("Top level Links", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => true,
    ),
    array(
        'id' => 'cssvar116',
        'name' => __("Top level Links - Active", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => false,
        'font-size'       => false,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => false,
        'font-variant'    => false,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => false,
        'word-spacing'    => false,
        'letter-spacing'  => false,
        'cufon'           => true,
    ),
    array(
        'id' => 'cssvar54',
        'name' => __("Top level Links - :hover", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => false,
        'font-size'       => false,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => false,
        'font-variant'    => false,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => false,
        'word-spacing'    => false,
        'letter-spacing'  => false,
        'cufon'           => true,
    ),
    array(
        'id' => 'cssvar55',
        'name' => __("Second level Links", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => true,
    ),
    array(
        'id' => 'cssvar56',
        'name' => __("Second level Links - :hover", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => false,
        'font-size'       => false,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => false,
        'font-variant'    => false,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => false,
        'word-spacing'    => false,
        'letter-spacing'  => false,
        'cufon'           => true,
    ),
    array(
        "type" => "endnosave"
    ),
    array(
        "type" => "justsave"
    ),
);

return array(
		'auto' => true,
		'name' => 'css',
		'options' => $options
);