<?php
$options = array (
	array(
        "name" => __("Slide Show Elements", 'ultimatum').'',
        "type" => "start"
		),
    array(
        'id' => 'cssvar105',
        'name' => __("Titles for Anything Slider and SlideDeck", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => false,
    ),
    array(
        'id' => 'cssvar100',
        'name' => __("Content for Anything Slider and SlideDeck", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => false,
    ),
    array(
        'id' => 'cssvar106',
        'name' => __("Caption Titles for Anything Slider and S3 Slider", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => false,
    ),
    array(
        'id' => 'cssvar107',
        'name' => __("Caption Content for Anything Slider and S3 Slider", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => false,
    ),
    array(
        "type" => "endnosave"
    ),
    array(
        "type" => "justsave"
    ),
);
return array(
    'auto' => true,
    'name' => 'css',
    'options' => $options
);