<?php
$options =array(
		array(
				"name" => __("Tabs", 'ultimatum'),
				"type" => "start"
		),
		array(
				"name" => __("Inactive Tab Background", 'ultimatum'),
				"id" => "cssvar86",
				"property" =>"background-color",
				"default" => "0",
				"type" => "color",
		),
		array(
				"name" => __("Hover Tab Background ", 'ultimatum'),
				"id" => "cssvar87",
				"property" =>"background-color",
				"default" => "0",
				"type" => "color",
		),
		array(
				"name" => __("Active Tab Background", 'ultimatum'),
				"id" => "cssvar88",
				"property" =>"background-color",
				"default" => "0",
				"type" => "color",
		),
		array(
				"name" => __("Content Background ", 'ultimatum'),
				"id" => "cssvar89",
				"property" =>"background-color",
				"default" => "",
				"type" => "color"
		),
    array(
        'id' => 'cssvar86',
        'name' => __("Default Tab Title", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => false,
    ),
    array(
        'id' => 'cssvar88',
        'name' => __("Active Tab Title", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => false,
        'font-size'       => false,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => false,
        'font-variant'    => false,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => false,
        'word-spacing'    => false,
        'letter-spacing'  => false,
        'cufon'           => true,
    ),
    array(
        'id' => 'cssvar87',
        'name' => __("Tab Title :hover", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => false,
        'font-size'       => false,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => false,
        'font-variant'    => false,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => false,
        'word-spacing'    => false,
        'letter-spacing'  => false,
        'cufon'           => true,
    ),
    array(
        'id' => 'cssvar89',
        'name' => __("Tab Content", 'ultimatum'),
        'type' => 'typography',
        'font-family'     => true,
        'font-size'       => true,
        'font-weight'     => true,
        'font-style'      => true,
        'text-align'      => false,
        'text-transform'  => true,
        'font-variant'    => true,
        'text-decoration' => true,
        'color'           => true,
        'line-height'     => true,
        'word-spacing'    => true,
        'letter-spacing'  => true,
        'cufon'           => false,
    ),
    array(
        "type" => "endnosave"
    ),
    array(
        "type" => "justsave"
    ),
);
return array(
		'auto' => true,
		'name' => 'css',
		'options' => $options
);